@startuml
'https://plantuml.com/class-diagram

class Company {
}


class ConsultUsersInTheWaitingRoomUI

class ConsultUsersInTheWaitingRoomController{
}


left to right direction

ConsultUsersInTheWaitingRoomUI .> ConsultUsersInTheWaitingRoomController
ConsultUsersInTheWaitingRoomController .> Company

@enduml