@startuml
'https://plantuml.com/class-diagram




class ConsultUsersInTheWaitingRoomUI

class ConsultUsersInTheWaitingRoomController

class Arrivals


left to right direction

ConsultUsersInTheWaitingRoomUI .> ConsultUsersInTheWaitingRoomController
ConsultUsersInTheWaitingRoomController .> Arrivals

@enduml