@startuml
autonumber
actor "Nurse" as N

activate N
N -> ":System" : asks to consult the users in the waiting room of a vaccination centre
activate ":System"
":System" --> N : requests the vaccination centre
deactivate ":System"

N -> ":System" : chooses the option containing the requested vaccination centre
activate ":System"
":System" --> N : shows the users in that vaccination centre's waiting room
deactivate ":System"

@enduml