@startuml
'https://plantuml.com/class-diagram




class ConsultUsersInTheWaitingRoomUI

class ConsultUsersInTheWaitingRoomController{
+getVaccinationCenter()
+listOfUsersInTheWaitingRoom(VaccinationCenter vaccinationCenter)
}

class Arrivals

class Company

class SnsUser


left to right direction

ConsultUsersInTheWaitingRoomUI .> ConsultUsersInTheWaitingRoomController
ConsultUsersInTheWaitingRoomController .> Arrivals
ConsultUsersInTheWaitingRoomController .> Company
Company -> SnsUser


@enduml