@startuml
'https://plantuml.com/class-diagram


class Admin {

}

class User {
SNSNumber : int
}

class Receptionist {

}

class Nurse {

}

class CenterCoordinator {

}

Admin "1" -- "1" User : configures and manages  >
Admin "1" - "1" Nurse : configures and manages >
Admin "1" -l- "1" Receptionist : configures and manages >
Admin "1" -- "1" VaccinatonCenter : configures and manages >
Admin "1" -up-- "1" CenterCoordinator : configures and manages >
Admin "1" -right-- "*" TypeOfVaccine : configures and manages >
Admin -- Vaccine


class VaccinatonCenter {
-name : String
-address : String
-phoneNumber : int
-emailAddress : String
-faxNumber : int
-websiteAddress : String
-openingHour : int
-closingHour : int
-slotDuration : int
-vaccinesPerSlot : int
-coordinator : Coordinator
}

class MassVaccinationCenter extends VaccinatonCenter {

}

class HealthcareCenter extends VaccinatonCenter {
ARE : String
AGES : String
}

class Vaccine {
brand : String
}

class DosageScheme {
-numberOfDoses : int
-dosage : int
-age : int
-intervalBetweenVaccines : int
}

class TypeOfVaccine {
virus : String
}


Vaccine "1" -- "*" DosageScheme : has a >
TypeOfVaccine "1" -- "*" Vaccine :is of >
Vaccine "1" --- "*" VaccinatonCenter : is administered on >

class DigitalCertificate

Nurse "1" -left "*" DigitalCertificate : Delivers >
User "1" -- "*" DigitalCertificate : Requests >

class ScheduleVaccine

User "*" -- "*" ScheduleVaccine
Receptionist "*" - "*" ScheduleVaccine


class AppointmentList

Receptionist "1" -l- "*" AppointmentList : checks >


class UsersReady

Receptionist -- UsersReady : atualizes >
Nurse -- UsersReady : checks >


class VaccineInformation
class AdverseReactions

left to right direction

VaccineInformation "*" - "*" AdverseReactions
(VaccineInformation, AdverseReactions) . Nurse : registers


class ManageVaccinationProcess

CenterCoordinator "1" -- "1" ManageVaccinationProcess : has to >

@enduml