@startuml
'https://plantuml.com/class-diagram

class Vaccine {
-brand : String

}


class DosageScheme {
-numberOfDoses : int
-dosage : int
-age : int
-intervalBetweenVaccines : int
}

Vaccine "1  " -- "1" DosageScheme : has a >

class TypeOfVaccine {
-virus : String
}

Vaccine "*" -- "1 " TypeOfVaccine : is of >


class VaccinationCenter {
-name : String
-address : String
-phoneNumber : int
-emailAddress : String
-faxNumber : int
-websiteAddress : String
-openingHour : int
-closingHour : int
-slotDuration : int
-vaccinesPerSlot : int
-coordinator : Coordinator
}

Vaccine "*" -- "1" VaccinationCenter : is administred on >
class HealthcareCenter extends VaccinationCenter {
-ARS : String
-AGES : String
}

class MassVaccinationCenter extends VaccinationCenter {

}

class Nurse extends ApplicationUser{

}

class ApplicationUser{
-password : String
}

class Administrator extends ApplicationUser{

}

class Receptionist extends ApplicationUser {

}

class CenterCoordinator extends ApplicationUser {

}

class SnsUser extends ApplicationUser {
snsUserNumber : int
}

class Application {

}

' Da para usar u - d -r - l dentro dos traços para design

Application "1" ---- "*" Administrator : is managed by >
Administrator "" ---- "" CenterCoordinator : configures and manages >
Administrator "" ---- "" VaccinationCenter : configures and manages >
Administrator "" ---- "" TypeOfVaccine : configures and manages >
Administrator "" ---- "" Vaccine : configures and manages >
Administrator "" ---- "" Nurse : configures and manages >
Administrator "" ---- "" Receptionist : configures and manages >
Nurse "1" ---- "*" Vaccine : administers >
'DUVIDA
SnsUser "" ---- "" VaccineAppointment : schedules >

SnsUser "*" ---- "1" Application : Requests authorization to send SMS <
Receptionist "1" -- "*" VaccineAppointment :schedules >
Receptionist "1" -- "*" VaccineAppointment :confirms >

Nurse "*" --  "1" WaitingList : checks >

class VaccineAppointment {

}

class WaitingList {

}



@enduml