@startuml
'https://plantuml.com/use-case-diagram
'!pragma layout smetana

left to right direction
title Usecase Diagram
skinparam titleBorderRoundCorner 20
skinparam titleBorderThickness 2
skinparam arrowThickness 3

'**********User*************
Usecase UC27 as "Schedule Vaccine Appointment" #mediumSpringGreen;line:black
Usecase UC28 as "Obtain Vaccination Certificate" #mediumSpringGreen;line:black
Usecase UC29 as "Authorize DGS to send a message with\n information about the scheduled appointment" #mediumSpringGreen;line:black

:User: as U #mediumSpringGreen;line:mediumSpringGreen

U -d- UC27 #mediumSpringGreen
U -d- UC28 #mediumSpringGreen
U -d- UC29 #mediumSpringGreen





skinparam actorStyle Hollow
'**********Nurse*************
Usecase UC13 as "Check the list of SNS users in the vaccination"  #indianRed;line:black
Usecase UC14 as "Check User's info" #indianRed;line:black
Usecase UC15 as "Check User's health condition" #indianRed;line:black
Usecase UC16 as "Check User's scheduled vaccine type" #indianRed;line:black
Usecase UC17 as "Check User's vaccination history" #indianRed;line:black
Usecase UC18 as "Registers vaccination type" #indianRed;line:black
Usecase UC19 as "Registers vaccine name/brand" #indianRed;line:black
Usecase UC20 as "Registers vaccine lot number" #indianRed;line:black
Usecase UC21 as "Issue a vaccination certificate" #indianRed;line:black
Usecase UC22 as "Record adverse reactions" #indianRed;line:black
Usecase UC23 as "Schedule vaccine for a User" #indianRed;line:black
Usecase UC24 as "Get system instructions regarding the vaccine" #indianRed;line:black

:Nurse: as N #white;line:indianRed
N -d- UC13 #indianRed
N -d- UC14 #indianRed
N -d- UC15 #indianRed
N -d- UC16 #indianRed
N -d- UC17 #indianRed
N -d- UC18 #indianRed
N -d- UC19 #indianRed
N -d- UC20 #indianRed
N -d- UC21 #indianRed
N -d- UC22 #indianRed
N -d- UC23 #indianRed
N -d- UC24 #indianRed

skinparam actorStyle awesome


'**********Recepcionist*************
Usecase UC25 as "Registers the arrival of a user" #orange;line:black
Usecase UC26 as "Confirms that the user has the vaccine scheduled for that day and time \n using the SNS user number "  #orange;line:black

:Receptionist: as R #orange;line:orange
R -d- UC25  #orange;line:orange
R -d- UC26  #orange;line:orange


'**********Center Coordinator*************
Usecase UC10 as "Visualizes Vaccination Charts and Statistics" #lightblue;line:black
Usecase UC11 as "Generate Reports" #lightblue;line:black
Usecase UC12 as "Analyze data from other centers" #lightblue;line:black

:Center Coordinator: as CC #lightblue;line:lightblue;
CC -d- UC10 #lightblue;line:lightblue
CC -d- UC11 #lightblue;line:lightblue
CC -d- UC12 #lightblue;line:lightblue


'**********ADMINISTRATOR*************
Usecase UC1 as "Configures and manages type of vaccines"   #lightgrey;line:black
Usecase UC2 as "Configures and manages Vaccines"  #lightgrey;line:black
Usecase UC3 as "Configures and manages Vaccination Center"   #lightgrey;line:black
Usecase UC4 as "Configures and manages Employees"  #lightgrey;line:black
Usecase UC5 as "Registers Center" #lightgrey;line:black
Usecase UC6 as "Registers Centers Coordinators" #lightgrey;line:black
Usecase UC7 as "Registers SNS Users" #lightgrey;line:black
Usecase UC8 as "Registers Receptionists" #lightgrey;line:black
Usecase UC9 as "Registers Nurses" #lightgrey;line:black


:Administrator: as A #black;line:black
A -d- UC1 #black;line:black
A -d- UC2 #black;line:black
A -d- UC3 #black;line:black
A -d- UC4 #black;line:black
A -d- UC5 #black;line:black
A -d- UC6 #black;line:black
A -d- UC7 #black;line:black
A -d- UC8 #black;line:black
A -d- UC9 #black;line:black


'**********User*************



@enduml