@startuml
'https://plantuml.com/use-case-diagram
'!pragma layout smetana

left to right direction
title Usecase Diagram Beginning
skinparam actorStyle awesome
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2



'**********Nurse*************
Usecase UC13 as "Check the list of SNS users in the vaccination"
Usecase UC14 as "Check User's info"
Usecase UC15 as "Check User's health condition"
Usecase UC16 as "Check User's scheduled vaccine type"
Usecase UC17 as "Check User's vaccination history"
Usecase UC18 as "Registers vaccination type"
Usecase UC19 as "Registers vaccine name/brand"
Usecase UC20 as "Registers vaccine lot number"
Usecase UC21 as "Issue a vaccination certificate"
Usecase UC22 as "Record adverse reactions"
Usecase UC23 as "Schedule vaccine for a User"
Usecase UC24 as "Get system instructions regarding the vaccine"

:Nurse: as N
N -d- UC13
N -d- UC14
N -d- UC15
N -d- UC16
N -d- UC17
N -d- UC18
N -d- UC19
N -d- UC20
N -d- UC21
N -d- UC22
N -d- UC23
N -d- UC24



'**********Recepcionist*************
Usecase UC25 as "Registers the arrival of a user"
Usecase UC26 as "Confirms that the user has the vaccine scheduled for that day and time \n using the SNS user number "

:Receptionist: as R
R -d- UC25
R -d- UC26



'**********Center Coordinator*************
Usecase UC10 as "Visualizes Vaccination Charts and Statistics"
Usecase UC11 as "Generate Reports"
Usecase UC12 as "Analyze data from other centers"

:Center Coordinator: as CC
CC -d- UC10
CC -d- UC11
CC -d- UC12



'**********DGS ADMINISTRATOR************
Usecase UC5 as "Registers Center"
Usecase UC6 as "Registers Centers Coordinators"
Usecase UC7 as "Registers SNS Users"
Usecase UC8 as "Registers Receptionists"
Usecase UC9 as "Registers Nurses"

:DGS Administrator: as D
D -d- UC5
D -d- UC6
D -d- UC7
D -d- UC8
D -d- UC9



'**********ADMINISTRATOR*************
Usecase UC1 as "Configures and manages type of vaccines"
Usecase UC2 as "Configures and manages Vaccines"
Usecase UC3 as "Configures and manages Vaccination Center"
Usecase UC4 as "Configures and manages Employees"

:Administrator: as A
A -d-> UC1
A -d-> UC2
A -d-> UC3
A -d-> UC4



'**********User*************



@enduml