@startuml
'https://plantuml.com/class-diagram

class DataFromLegacySystemUI{
+run()
+runLoadCSV()
+getListOfSNSUsers()
+validateFileFormat(path)
+validateCSVData(values)
+fillSNSUserDto(csvData)
}

class App{
}

class DataFromLegacySystemController{
+createSNSUser(SNSUserDto)
+saveSNSUser(SNSUserDto)
+getSNSUserList()
}

class Company{
+createSNSUser(SNSUserDto)
+saveSNSUser(SNSUserDto)
+getSNSUserList()
}

class SNSUserStore{
-strName
-strSex
-strBirthDate
-strAddress
-strPhoneNumber
-strEmail
-snsUserNumber
-strCitizenCardNumber
-strPassword
}

class ReadLegacyDataFile{
-strName
-strSex
-strBirthDate
-strAddress
-strPhoneNumber
-strEmail
-snsUserNumber
-strCitizenCardNumber
-strPassword
+getSnsUserNumber()
+getStrEmail()
+getStrPhoneNumber()
+getStrCitizenCardNumber()
+validateSNSUser()
+toString()
}






@enduml