@startuml
autonumber

actor "Receptionist" as R

participant ":RegisterArrivalOfASNSUserUI" as UI
participant ":RegisterArrivalOfASNSUserController" as CTRL
participant ":Arrival" as A
participant ":Company" as C

activate R

R -> UI : asks to register an arrival
activate UI

UI --> R : requests data (SNS number, Vaccination Center of the Receptionist and of the User)
deactivate UI

R -> UI : types requested data
activate UI

UI -> CTRL : checkRequirementsForRegistration(SNS number, Vaccination Center User, Vaccination Center Receptionist, Date)
activate CTRL

CTRL -> A : checkRequirementsForRegistration(SNS number, Vaccination Center User, Vaccination Center Receptionist, Date)
activate A

CTRL --> UI : result

UI --> R: shows the result

deactivate A

deactivate CTRL
deactivate UI


R -> UI : registers the arrival depending on the result
activate UI

UI -> CTRL : registerArrival(SNS number, Vaccination Center)
activate CTRL

CTRL -> C : registerArrival(SNS number, Vaccination Center)
activate C




CTRL --> UI: result

UI --> R : informs operation success

deactivate C
deactivate CTRL
deactivate UI
deactivate R


@enduml