@startuml
'https://plantuml.com/class-diagram

class Company {
+checkAppointment(int SNSNumber)
+registerArrival(int SNSNumber)
}


class RegisterArrivalOfSNSUserUI

class RegisterArrivalOfSNSUserController{
+checkAppointment(int SNSNumber)
+registerArrival(int SNSNumber)
}


left to right direction

RegisterArrivalOfSNSUserController -> Company
RegisterArrivalOfSNSUserUI - RegisterArrivalOfSNSUserController

@enduml