@startuml
autonumber

actor "Receptionist" as R

participant ":RegisterArrivalOfASNSUserUI" as UI
participant ":RegisterArrivalOfASNSUserController" as CTRL
participant ":Company" as C

activate R

R -> UI : asks to check if an SNS user has an appointment
activate UI

UI --> R : requests data (SNS number)
deactivate UI

R -> UI : types requested data
activate UI

UI -> CTRL : checkUserAppointment(SNS number)
activate CTRL

CTRL -> C : checkUserAppointment(SNS number)
activate C

CTRL --> UI : result

UI --> R: shows the result

deactivate C
deactivate CTRL
deactivate UI


R -> UI : registers the arrival if there is an appointment
activate UI

UI -> CTRL : registerArrival(SNS number)
activate CTRL

CTRL -> C : registerArrival(SNS number)
activate C




CTRL --> UI: result

UI --> R : informs operation success

deactivate C
deactivate CTRL
deactivate UI
deactivate R


@enduml