@startuml
autonumber
actor "Receptionist" as R

activate R

R -> ":System" : asks to check if an SNS user has an appointment
activate ":System"
":System" --> R : requests data (SNS number)
deactivate ":System"

R -> ":System" : types requested data
activate ":System"
":System" --> R : shows the data
deactivate ":System"

R -> ":System" : search for appointment through the SNS number
activate ":System"
":System" --> R : result
deactivate ":System"

R -> ":System" : Registers arrival depending on the result
activate ":System"
":System" --> R : informs operation success
deactivate ":System"

deactivate R

@enduml