@startuml

autonumber
actor "Administrator" as A

activate A
A -> ":System" : asks to specify a new vaccine

activate ":System"
":System" --> A : requests data (name of the vaccine)
deactivate ":System"

A -> ":System" : inputs requested data

activate ":System"

loop while adding age groups
 ":System" --> A : requests data (age limits, number of doses,\n vaccine dosage, time interval between vaccines )
end

deactivate ":System"

A -> ":System" : types requested data
activate ":System"
":System" --> A : informs operation success
deactivate ":System"

deactivate A

@enduml