@startuml

autonumber
actor "CenterCoordinator" as CC

activate CC

CC -> ":System" : asks to analze the performance of a center

activate ":System"
":System" --> CC : request the selection of a date and a time interval
deactivate ":System"
CC -> ":System" : selects the date and types the time interval

activate ":System"
":System" --> CC : shows the data requested
deactivate ":System"


deactivate CC

@enduml