@startuml
'https://plantuml.com/sequence-diagram

autonumber

autonumber

activate Administrator

Administrator -> System: Asks to create a Vaccination Center
activate System
Administrator <-- System: Requests data (i.e. name, address, phone number, e-mail, fax number, website address, opening and closing hours, slot duration and vaccines per slot)
deactivate System

Administrator -> System: Types requested data
activate System
Administrator <-- System: Shows data and requests confirmation
deactivate System

Administrator -> System: Confirms data
activate System
Administrator <-- System: Informs if the operation was successful
deactivate System

deactivate Administrator
@enduml