@startuml
'https://plantuml.com/class-diagram
'!pragma layout smetana

class Company

class VaccineType{
==-description
==-code
==-vaccineTechnology
}

class Vaccine{
==-brand
}

class VaccinationCenter{
==-name
==-address
==-phoneNumber
==-emailAddress
==-faxNumber
==-websiteAddress
==-openingHour
==-closingHour
==-slotDuration
==-vaccinesPerSlot
}

class Coordinator

class MassVaccinationCenter extends VaccinationCenter{

}

class HealthcareCenter extends VaccinationCenter{
==-ARS
==-AGES
}

Company "1" -down- "*" VaccinationCenter: owns >
MassVaccinationCenter "1" -down- "1" Coordinator: has >
HealthcareCenter "1" -down- "1" Coordinator: has >
MassVaccinationCenter "1" --down-- "1" VaccineType: administers >
HealthcareCenter "1" -down- "*" VaccineType: administers >
Vaccine "*" --left-- "1" VaccineType: is of >

@enduml