@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

class Administrator

class VaccinationCenter{
==-name
==-address
==-phoneNumber
==-emailAddress
==-faxNumber
==-websiteAddress
==-openingHour
==-closingHour
==-slotDuration
==-vaccinesPerSlot
}

class Coordinator

class MassVaccinationCenter extends VaccinationCenter{

}

class HealthcareCenter extends VaccinationCenter{
==-ARE
==-AGES
}

VaccinationCenter "1" --- "1" Coordinator: has
Administrator "1" --- "*" VaccinationCenter: creates

@enduml