@startuml
'https://plantuml.com/class-diagram

class Administrator{

}

class VaccinationCenter{
==-name
==-address
==-phoneNumber
==-emailAddress
==-faxNumber
==-websiteAddress
==-openingHour
==-closingHour
==-slotDuration
==-vaccinesPerSlot
==-coordinator
}

Administrator "*" -- "*" VaccinationCenter : configures and manages >

class MassVaccinationCenter extends VaccinationCenter{

}

class HealthcareCenter extends VaccinationCenter{
==-ARE
==-AGES
}

@enduml