@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

class Company {
+createVaccinationCenter(name, address, phone number, email address, fax number, website address, opening hour, closing hour, slot duration, vaccines per slot)
+validateVaccinationCenter(name, address, phone number, email address, fax number, website address, opening hour, closing hour, slot duration, vaccines per slot)
}

class VaccinationCenter {
String name
String address
double phoneNumber
String emailAddress
double faxNumber
String websiteAddress
int openingHour
int closingHour
int slotDuration
int vaccinesPerSlot
}

class CreateNewVaccinationCenterUI

class CreateNewVaccinationCenterController{
+createVaccinationCenter(name, address, phone number, email address, fax number, website address, opening hour, closing hour, slot duration, vaccines per slot)
+validateVaccinationCenter(name, address, phone number, email address, fax number, website address, opening hour, closing hour, slot duration, vaccines per slot)
}
left to right direction

CreateNewVaccinationCenterUI - CreateNewVaccinationCenterController
CreateNewVaccinationCenterController -> Company
Company .> VaccinationCenter

@enduml