@startuml
'https://plantuml.com/class-diagram

class Company {
+createVaccineType(type)
+validateVaccineType(type)?
}

class SpecifyNewVaccineTypeUI

class SpecifyNewVaccineTypeController{
+createVaccineType(type)
+saveVaccineType(type)
}

class VaccineType {
String name
+VaccineType(type)
+validateVaccineType(type)
+saveVaccineType(type)
}

left to right direction

SpecifyNewVaccineTypeUI - SpecifyNewVaccineTypeController
SpecifyNewVaccineTypeController --> Company
Company .> VaccineType
SpecifyNewVaccineTypeController -> VaccineType

@enduml