@startuml
'https://plantuml.com/sequence-diagram

autonumber

activate Administrator
Administrator -> System: Asks to load a CSV file containing User information
activate System
Administrator <-- System: Requests the path of the CSV file
deactivate System

Administrator -> System: Types the path of the CSV file
activate System
Administrator <-- System: Informs if the path is valid
Administrator <-- System: If the path is valid then informs if the User data contained in the CSV is valid.

@enduml