@startuml

autonumber

actor Nurse as N

participant ":RecordVaccineAdministrationUI" as UI
participant ":RecordVaccineAdministrationController" as CTRL
participant "company\n:Company" as C
participant "vaccinationCenter\n:VaccinationCenter" as VC
participant "snsUser\n:SnsUser" as SU
participant "vaccineBulletinList\nList<VaccineBulletin>" as L

activate N
N -> UI : asks to record the administration of a vaccine to an SNS user
activate UI

UI -> CTRL : vaccinationCenterList = getVaccinationCentersNameList()
activate CTRL
CTRL -> C : vaccinationCenterList = getVaccinationCenters()
activate C
deactivate CTRL
deactivate C

UI --> N : shows a list with the available vaccination centers
deactivate UI

N -> UI : selects one vaccination center
activate UI
UI -> CTRL : setVaccinationCenter(vaccinationCenterIndex)
activate CTRL
CTRL -> C : vaccinationCenter = getVaccinationCenters().get(index)
activate C
deactivate C
deactivate CTRL

UI -> CTRL : setArrivalsList = vaccinationCenter.getArrivalsList()
activate CTRL
CTRL -> VC : arrivalsList = getArrivalsList()

activate VC
deactivate VC
deactivate CTRL

 UI --> N : shows a list with the users available in arrivals list
deactivate UI
N -> UI : selects one user

activate UI
UI -> CTRL : setVaccineType(arrivalsListUserIndex)
activate CTRL
CTRL -> CTRL : doseNumber = findLastDoseOfVaccineType()
alt It´s user´s first dose
UI -> CTRL : vaccineList = getVaccineNameList()
CTRL -> C : vaccineList = getVaccineList()
activate C
deactivate C
loop Validate User Age Group
UI --> N : shows a list with the available vaccines
N -> UI : selects one vaccine
UI -> CTRL : vaccineName = vaccineList(vaccineIndex)
CTRL -> SU : userAge = snsUser.getSnsUserAge()
CTRL -> CTRL : validate user age group
end
end
deactivate CTRL
UI --> N : shows dosage for respective dose
loop Validate Lot Number
UI --> N :requests vaccine´s lot number
N -> UI : introduces vaccine´s lot number

UI -> CTRL : vaccine´s lot number
activate CTRL
CTRL -> CTRL : validate vaccine´s lot number

end

UI -> CTRL : VaccineBulletinDto()

CTRL -> SU : addVaccineBulletin(VaccineBulletin)
activate SU
SU -> L : addVaccineBulletin(VaccineBulletin)
activate L

UI -> CTRL : printRecoveryTime()

UI --> N : informs that vaccine administration is completed
deactivate L
deactivate SU
deactivate CTRL
deactivate UI
deactivate N
@enduml