@startuml

autonumber

actor Receptionist as R

participant ":ScheduleVaccineUI" as UI
participant ":ScheduleVaccineController" as CTRL
participant "vaccinationCenter\n:VaccinationCenter" as VC
participant "scheduledVaccineDtoMapper\n:ScheduledVaccineMapper" as M
participant "scheduledVaccineDto\n:ScheduledVaccineDto" as DTO
participant "appointmentsList\nList<ScheduledVaccine>" as L

'participant "Utils" as U

activate R
R -> UI : asks to schedule a vaccine


activate UI
UI-> R : requests data (SNS number)
deactivate UI
R-> UI : types SNS user number


activate UI
UI --> R : shows a list with the available vaccination centers
deactivate UI
R -> UI : selects one vaccination center


activate UI
 UI --> R : shows a list with the Vaccine Types available
deactivate UI
R -> UI : selects one Vaccine Type


activate UI
 UI --> R : shows a list with all the dates available
deactivate UI
R -> UI : selects one date


activate UI
 UI --> R : shows a list with all the slots available
deactivate UI
R -> UI : selects one slot



activate UI
UI -> CTRL : validateAppointment(scheduleVaccineDto, vaccinationCenter)

activate CTRL
CTRL -> CTRL : dataIsAllFilled(scheduleVaccineDto)
activate CTRL
deactivate CTRL
CTRL -> VC : validateAppointment(scheduleVaccineDto)

activate VC
VC ---> CTRL : result
deactivate VC


CTRL ---> UI : result
deactivate CTRL

UI -> R : shows the data and requests confirmation
deactivate UI

R -> UI : confirms the data
activate UI

UI -> CTRL : scheduledVaccine(scheduleVaccineDto, vaccinationCenter)
activate CTRL


CTRL -> VC : validateAppointment(scheduleVaccineDto)

activate VC
VC ---> CTRL : result
deactivate VC
CTRL -> M : scheduledVaccine = createScheduledVaccine(scheduleVaccineDto)
activate M
note over M, DTO
Several steps to extract data from the DTO
end note
M -> "scheduledVaccine\n:ScheduledVaccine" ** : dtoToDomain(scheduleVaccineDto)
deactivate M

CTRL -> VC : addAppointment(scheduledVaccine)
activate VC


VC -> L : addAppointment(scheduledVaccine)
activate L
L --> VC : result

deactivate L

VC --> CTRL : result

deactivate VC










CTRL ---> UI : result
UI --> R : informs operation success
deactivate UI
deactivate R
@enduml