@startuml

autonumber

actor SNSUser as U

participant ":ScheduleVaccineUI" as UI
participant ":ScheduleVaccineController" as CTRL
participant "vaccinationCenter\n:VaccinationCenter" as VC
participant "scheduledVaccineDtoMapper\n:ScheduledVaccineMapper" as M
participant "scheduledVaccineDto\n:ScheduledVaccineDto" as DTO
participant "appointmentsList\nList<ScheduledVaccine>" as L

'participant "Utils" as U

activate U
U -> UI : asks to schedule a vaccine


activate UI
UI-> U : requests data (SNS number)
deactivate UI
U-> UI : types SNS user number


activate UI
UI --> U : shows a list with the available vaccination centers
deactivate UI
U -> UI : selects one vaccination center


activate UI
 UI --> U : shows a list with the Vaccine Types available
deactivate UI
U -> UI : selects one Vaccine Type


activate UI
 UI --> U : shows a list with all the dates available
deactivate UI
U -> UI : selects one date


activate UI
 UI --> U : shows a list with all the slots available
deactivate UI
U -> UI : selects one slot



activate UI
UI -> CTRL : validateAppointment(scheduleVaccineDto, vaccinationCenter)

activate CTRL
CTRL -> CTRL : dataIsAllFilled(scheduleVaccineDto)
activate CTRL
deactivate CTRL
CTRL -> VC : validateAppointment(scheduleVaccineDto)

activate VC
VC ---> CTRL : result
deactivate VC


CTRL ---> UI : result
deactivate CTRL

UI -> U : shows the data and requests confirmation
deactivate UI

U -> UI : confirms the data
activate UI

UI -> CTRL : scheduledVaccine(scheduleVaccineDto, vaccinationCenter)
activate CTRL


CTRL -> VC : validateAppointment(scheduleVaccineDto)

activate VC
VC ---> CTRL : result
deactivate VC
CTRL -> M : scheduledVaccine = createScheduledVaccine(scheduleVaccineDto)
activate M
note over M, DTO
Several steps to extract data from the DTO
end note
M -> "scheduledVaccine\n:ScheduledVaccine" ** : dtoToDomain(scheduleVaccineDto)
deactivate M

CTRL -> VC : addAppointment(scheduledVaccine)
activate VC


VC -> L : addAppointment(scheduledVaccine)
activate L
L --> VC : result

deactivate L

VC --> CTRL : result

deactivate VC



CTRL ---> UI : result
UI --> U : informs operation success and shows appointment information

UI -> U : asks if the user wants to receive an SMS with the appointment information
deactivate UI

U -> UI : authorizes the application to send him an SMS
activate UI
UI -> UI : printAppointmentToFile(scheduledVaccineDto, vaccinationCenter)
activate UI
deactivate UI
UI ---> U : informs operation success
deactivate UI
deactivate U
@enduml