@startuml

autonumber

actor Receptionist as R

participant ":SpecifyVaccineAndAdminProcessUI" as UI
participant ":SpecifyVaccineAndAdminProcessController" as CTRL
participant "company\n:Company" as C
participant "administrationProcess\n:AdministrationProcess" as AP
participant "vaccine\n:Vaccine" as V
participant "vaccineAndAdminProcessDto\n:VaccineAndAdminProcessDto" as DTO

activate R
R -> UI :asks to specify a new vac and its administration process

activate UI
UI-> R : shows a list with all the Vaccine Types available
deactivate UI


R-> UI : selects one Vaccine Type



activate UI
UI --> R : requests data (id, name, brand, vaccineType)
deactivate UI

R -> UI : inputs requested data

activate UI

loop while adding age groups
 UI --> R : requests data (age limits, number of doses,\n vac dosage, time interval between vaccines )

deactivate UI
note right
data for the Administration Process
end note


R -> UI : types requested data
activate UI

end



activate UI
UI -> CTRL : specifyNewVaccineAndAdminProcess(vaccineAndAdminProcessDto)

activate CTRL
CTRL -> C : specifyNewVaccineAndAdminProcess(vaccineAndAdminProcessDto)

activate C
C -> AP : adminProcess = create(ageGroups, numberOfDoses, dosage, timeIntervalBetweenVaccines)

note over C, DTO : Several interactions to extract data from DTO.


activate AP
deactivate AP

C -> AP : validateAdministrationProcess(adminProcess)
activate AP
deactivate AP


C -> V : vac = create(name, id, brand, adminProcess, vaccineType)
note over C, DTO : Several interactions to extract data from DTO.

activate V
deactivate V

C -> V : validateVaccine(vac)
activate V
deactivate V
C --> CTRL : result
CTRL --> UI : result
deactivate CTRL
deactivate C
UI --> R : shows the data and requests confirmation
deactivate UI
R -> UI : confirms the data
activate UI
UI --> CTRL : saveVaccine(vaccineAndAdminProcessDto)

activate CTRL

CTRL -> C : saveVaccine(vaccineAndAdminProcessDto)

activate C
C -> AP : adminProcess = createAdministrationProcess(adminProcess)
activate AP
deactivate AP
C -> V :vac = create(name, id, brand, adminProcess, vaccineType)
activate V
deactivate V

C -> C : addVaccine(vac)



C --> CTRL : result
CTRL ---> UI : result
UI --> R : informs operation success
deactivate UI
deactivate R
@enduml